COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAFLAGS+=-flto
NKRO_ENABLE = yes
OS_DETECTION_ENABLE = yes
RGBLIGHT_ENABLE = no
SRC += features/cross_os_compat.c
SRC += features/zen_nav.c
